[tool.poetry]
name = "python-homework-4"
version = "0.1.0"
description = "Shop model"
authors = ["edkirill <edkirill@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
